# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Decouplio
email: differencialx@gmail.com
description: >-
  Decouplio is a zero dependency,
  thread safe and framework agnostic gem
  designed to encapsulate application
  business logic. It's reverse engineered
  through TDD and inspired by such frameworks
  and gems like Trailblazer, Interactor.
baseurl: "/decouplio.github.io"
url: "https://differencialx.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: differencialx
github_username:  differencialx
aux_links:
  "GitHub Repo":
    - "https://github.com/differencialx/decouplio"
# Build settings
theme: just-the-docs
logo: '/assets/images/logo_web.png'

plugins:
  - jekyll-mermaid
  - jekyll-sitemap

mermaid:
  src: '../vendor/mermaid.js'

search.heading_level: 3
search.previews: 4

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - examples/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
